- name: 创建 data 文件夹
  ansible.builtin.file:
    path: $HOME/data
    state: directory
    mode: '0666'

- name: 上传备份脚本
  copy:
    src: backup.sh
    dest: $HOME/data/backup.sh
    mode: '0755'

- name: 运行备份全部
  shell: $HOME/data/backup.sh {{client_id}} {{client_secret}} {{tenant_id}} {{software_name}}
  register: my_output # <- Registers the command output.
  changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.
  tags: backup