- name: Ensure the destination directory exists
  ansible.builtin.file:
    path: /root/alist
    state: directory
    mode: '0666'

- name: Ensure the destination directory exists
  ansible.builtin.file:
    path: /media/U盘
    state: directory
    mode: '0755'

- name: copy alist db files
  copy:
    src: data.db
    dest: /root/alist/data.db
    mode: '0666'

- name: copy alist cinfig files
  copy:
    src: config.json
    dest: /root/alist/config.json
    mode: '0755'

- name: docker Install alist
  ansible.builtin.raw: docker run -d --restart=always -v /media/U盘:/media/U盘 -v /root/alist:/opt/alist/data -p 5244:5244 -e PUID=0 -e PGID=0 -e UMASK=022 --name="alist" xhofe/alist:latest
  register: my_output # <- Registers the command output.
  changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.
  tags: install_alist