FROM python:3
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && sh -c "$(curl -L https://hubmirror.v2raya.org/raw/mzz2017/gg/main/release/go.sh)" \
    && gg config -w subscription=https://xn--5hqx9equq.com/api/v1/client/subscribe?token=e87ad20e1f17567da8b216b5d4543109 \
    && gg apt-get install -y sshpass \
    && gg pip3 install ansible \
    ansible-lint \
    && apt-get clean -y