FROM python:3
RUN apt install apt-transport-https ca-certificates\n \
    && echo deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye main contrib non-free\n \
    deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-updates main contrib non-free\n \
    deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-backports main contrib non-free\n \
    deb https://mirrors.tuna.tsinghua.edu.cn/debian-security bullseye-security main contrib non-free\n \
    >/etc/apt/sources.list \
    && apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && sh -c "$(curl -L https://hubmirror.v2raya.org/raw/mzz2017/gg/main/release/go.sh)" \
    && gg config -w subscription=https://xn--5hqx9equq.com/api/v1/client/subscribe?token=e87ad20e1f17567da8b216b5d4543109 \
    && gg apt-get install -y sshpass \
    && gg pip3 install ansible \
    && ansible-lint \
    && apt-get clean -y